#!/usr/bin/env bash
#
# is it best run via:
# $ nix run .#init

set -euo pipefail

go_to_root_of_git() {
    local root
    root=$(git rev-parse --show-toplevel)
    echo "INFO: Changing to git root: $root" >&2
    cd "$root"
}

get_zephyr() {
    parameter="$1"
    jq -r '.nodes.zephyr.original.'"$parameter" <flake.lock
}

get_zephyr_ref() {
    get_zephyr "ref"
}

get_zephyr_remote() {
    get_zephyr "owner"
}

get_zephyr_name() {
    get_zephyr "repo"
}

generate_west_yml() {
    local remote name ref
    remote="$1"
    name="$2"
    ref="$3"
    echo "INFO: Generating west.yml for ${remote}/${name} @ ${ref}"
    cat <<EOF >app/.tmp.west.yml
# Auto-generated by init.sh, Do not edit!
manifest:
  defaults:
    remote: ${remote}
  remotes:
    - name: ${remote}
      url-base: https://github.com/${remote}
  projects:
    - name: ${name}
      remote: ${remote}
      revision: ${ref}
      clone-depth: 1
      import: true
  self:
    path: app
EOF
    # if generated file is different from existing, replace it
    if ! cmp -s app/.tmp.west.yml app/west.yml; then
        echo "ERROR: app/west.yml changed"
        diff app/west.yml app/.tmp.west.yml
        exit 1
    fi
    rm app/.tmp.west.yml
}

west_init_once() {
    if [ ! -d .west ]; then
        echo "INFO: Initializing west"
        west init -l app
    else
        echo "INFO: West already initialized"
    fi
}

west_update_if_was_not_updated_already_today() {
    local stamp_file
    stamp_file=".west/last_update_stamp"
    if [ -f "$stamp_file" ]; then
        if [ "$(date -r "$stamp_file" +%Y-%m-%d)" = "$(date +%Y-%m-%d)" ]; then
            echo "INFO: West was already updated today"
            return
        fi
    fi
    echo "INFO: Updating west"
    west update
    touch "$stamp_file"
}

regenerate_mermaild_svg() {
    echo "INFO: Regenerating mermaid SVG"
    mmdc -i - -o app/mermaid.StateMachine.svg -t neutral -b transparent <app/mermaid.StateMachine.mmd
}

main() {
    go_to_root_of_git
    local remote name ref
    remote=$(get_zephyr_remote)
    name=$(get_zephyr_name)
    ref=$(get_zephyr_ref)
    generate_west_yml "$remote" "$name" "$ref"
    west_init_once
    west_update_if_was_not_updated_already_today
    regenerate_mermaild_svg
}

main
