flowchart LR;

  subgraph ControlBox
    direction TB
    subgraph STM32H747I-DISCO
      STM32H747I
      ST-Link --> STM32H747I
      Joystick
      Display
    end
    STM32H747I-DISCO -->|Arduino UNO R3| X-NUCLEO-IDB05AI

    subgraph ControlBoard
      24Vto5V
    end
    24Vto5V -->|5V| STM32H747I-DISCO
    STM32H747I-DISCO -->|Arduino UNO R3| ControlBoard
  end

  PC -->|USB| ST-Link
  PC-. 5V .->ST-Link

  subgraph RailAssembly
    subgraph RailBoard
      direction TB 
      IMU
      RailBoardGnd
    end
    subgraph Rail
      StepperMotor
      PositioningSensor
      Camera
    end
    RailBoard -->|24V| StepperMotor
    RailBoard -->|ENA+| StepperMotor
    RailBoard -->|DIR+| StepperMotor
    RailBoard -->|Pul+| StepperMotor
    RailBoardGnd -->|Gnd| StepperMotor
    RailBoardGnd -->|ENA-| StepperMotor
    RailBoardGnd -->|DIR-| StepperMotor
    RailBoardGnd -->|Pul-| StepperMotor
  end

  ControlBoard -->|24V| RailBoard
  ControlBoard -->|Gnd| RailBoard
  ControlBoard -->|ENA+| RailBoard
  ControlBoard -->|DIR+| RailBoard
  ControlBoard -->|Pul+| RailBoard
  ControlBoard -->|???| RailBoard
  ControlBoard -->|???| RailBoard
  ControlBoard -->|???| RailBoard

  24V ---> 24Vto5V
  X-NUCLEO-IDB05AI-. bluetooth .->Camera

  style IMU stroke-dasharray: 5 5
  style PositioningSensor stroke-dasharray: 5 5