---
config:
---
flowchart LR;

  subgraph ControlBox
    direction LR 
    subgraph stm32h747i_disco
      MCU_Left@{ label: "stm32h747" }
      ST-Link --> MCU_Left
    end
    subgraph ControlBoard
      MAX3485_Left@{ label: "MAX3485, TTL -> RS485" };
      MCU_Left --->|TTL| MAX3485_Left
    end
    stm32h747i_disco -->|Arduino UNO R3| ControlBoard
    DISPLAY@{ label: "st_b_lcd40_dsi1_mb1166_a09" }
    stm32h747i_disco ---> DISPLAY
  end

  PC([PC])
  PC ==>|USB| ST-Link

  subgraph RailAssembly
    subgraph RailBoard
      direction TB 
      24Vto5V
      MAX3485_Right@{ label: "MAX3485, RS485 -> TTL" }
      MCU_Right@{ label: "XIAO nRF52840 Sense" }
      IMU@{label: "LSM6DSO"}
      MCU_Right -->|I2C| IMU
      MAX3485_Right -->|TTL| MCU_Right
      24Vto5V ===|5V| MCU_Right
    end
    subgraph Rail
      StepperMotor
      PositioningSensor
      Camera@{label: "A7Rv"}
    end

    24Vto5V =====|24V| StepperMotor
    MCU_Right    -->|ENA+| StepperMotor
    MCU_Right    -->|DIR+| StepperMotor
    MCU_Right    -->|PUL+| StepperMotor
  end

  cable@{ shape: das, label: ".... cable ...." }

  MAX3485_Left -->|A & B| cable
  cable -->|A & B| MAX3485_Right

  cable ===|5V & GND| 24Vto5V
  ControlBoard ===|5V & GND| cable

  24V@{ shape: bolt }
  24V ======|24V| StepperMotor
  MCU_Right-. bluetooth .->Camera

  style PositioningSensor stroke-dasharray: 5 5