flowchart LR;
    S0((S0));

    S_WAIT_FOR_CAMERA;

    subgraph S_PARENT_INTERACTIVE
      S_INTERACTIVE{S_INTERACTIVE}
    end
    
    subgraph S_PARENT_STACKING;
      S_STACK{S_STACK}
      S_STACK_MOVE;
      S_STACK_SETTLE;
      S_STACK_IMG;
    end

    S0 --> S_INTERACTIVE;
    S_INTERACTIVE -->|process command| S_INTERACTIVE;
    S_INTERACTIVE -->|start stack| S_STACK;
    S_INTERACTIVE <-----|done| S_STACK;
    S_STACK_MOVE --> S_STACK_SETTLE;
    S_STACK_SETTLE --> S_STACK_IMG;
    S_STACK_IMG --> S_STACK;
    S_STACK --> S_STACK_MOVE;