flowchart LR;
    S0((S0));

    subgraph S_PARENT_INTERACTIVE
      direction TB 
      S_INTERACTIVE{S_INTERACTIVE}
      S_INTERACTIVE_EVENT([S_INTERACTIVE_EVENT])
      S_INTERACTIVE --> S_INTERACTIVE_EVENT;
      S_INTERACTIVE_EVENT --> S_INTERACTIVE;
      S_INTERACTIVE_MOVE;
    end
    S0 --> S_INTERACTIVE;

    subgraph S_PARENT_STACKING;
      direction TB
      S_STACK{S_STACK}
      S_STACK_MOVE --> S_STACK;
      S_STACK --> S_STACK_SETTLE;
      S_STACK_SETTLE --> S_STACK_IMG;
      S_STACK_IMG --> S_STACK_MOVE;
    end
    S_STACK --->|done| S0;
    S_INTERACTIVE ---> S_STACK_MOVE;