name: Build

on:
  pull_request:
    branches:    
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zephyrproject-rtos/ci:v0.24.6
      options: '--entrypoint /bin/bash'
    env:
      ZEPHYR_SDK_INSTALL_DIR: /opt/toolchains/zephyr-sdk-0.15.2
      LLVM_TOOLCHAIN_PATH: /usr/lib/llvm-15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          persist-credentials: false

      - name: Environment Setup
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          git config --global user.email "bot@maxhbr.de"
          git config --global user.name "Maxhbr Bot"
          git config --global --add safe.directory "$(readlink -f .)"
          west init -l . || true
          west config --global update.narrow true
          west update

      - name: build
        run: |
          west build .