name: Build

on: push
  # pull_request:
  #   branches:    
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zephyrproject-rtos/ci:v0.26.8
      options: '--entrypoint /bin/bash'
    env:
      ZEPHYR_SDK_INSTALL_DIR: /opt/toolchains/zephyr-sdk-0.16.5-1
      LLVM_TOOLCHAIN_PATH: /usr/lib/llvm-16
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # with:
        #   ref: ${{ github.event.pull_request.head.sha }}
        #   fetch-depth: 0
        #   persist-credentials: false

      - name: Environment Setup
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          git config --global user.email "bot@maxhbr.de"
          git config --global user.name "Maxhbr Bot"
          git config --global --add safe.directory "$(readlink -f .)"
          ./init.sh

      - name: build
        run: |
          app/wio_terminal-build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: ./app/builds/wio_terminal
